name = "trainlocation-jrkyushu-timetable-cache"
main = "workers/jrkyushu_timetable_cache.js"
compatibility_date = "2026-05-26"

kv_namespaces = [
	{ binding = "JRKYUSHU_TIMETABLE_KV", id = "596c84a860634b73bf01185602c3917f" }
]

[triggers]
# Cloudflare cron is UTC. 19:30 UTC is 04:30 JST.
crons = [ "30 19 * * *" ]
