"use strict";
const fs = require("fs");
const path = require("path");
const { routes } = require("../js/keikyu_routes.js");
const root = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(root, "apk解析/keikyu_web_assets/trainPosControll.js"), "utf8");
// Parse the literal placement table only; never execute the downloaded script.
const start = source.indexOf(",C=");
const end = source.indexOf(",I=", start);
if (start < 0 || end < 0) throw new Error("Placement table boundaries changed");
const records = JSON.parse(source.slice(start + 3, end).replace(/([{,])([A-Za-z_][A-Za-z0-9_]*):/g, '$1"$2":'));
const nameKey = s => String(s || "").normalize("NFKC").replace(/ヶ/g, "ケ").replace(/\s/g, "");
for (const record of Object.values(records)) {
  const section = record.sectionName;
  const fromName = section.ssName || section.sectionFrom.map(v => v.value).join("");
  const toName = section.ssName || section.sectionTo.map(v => v.value).join("");
  record.projections = {};
  for (const route of routes) {
    const from = route.stations.find(s => nameKey(s.name) === nameKey(fromName));
    const to = route.stations.find(s => nameKey(s.name) === nameKey(toName));
    if (!from || !to || Math.abs(from.index - to.index) > 1) continue;
    const lower = Math.min(from.index, to.index);
    record.projections[route.rosen] = {
      base: "KEIKYU" + route.rosen + "P" + (from.index === to.index ? from.index : lower + "_" + (lower + 1)),
      name: from.index === to.index ? from.name : from.name + "→" + to.name + " 間",
      direction: from.index === to.index ? "" : from.index < to.index ? "D" : "U"
    };
  }
}
// U065 spans Shin-otsu in the source description; its official drawing anchor is KK65.
// Keep that upstream span name while using the interval below Shin-otsu on this map.
records.U065.projections["150"] = {
  base: "KEIKYU150P2_3", name: "北久里浜→堀ノ内 間", direction: "U"
};
fs.writeFileSync(path.join(root, "js/keikyu_position_map.js"),
  "// Generated by tools/generate_keikyu_position_map.js from the public web placement table.\n" +
  "(function(root) { const records = " + JSON.stringify(records, null, 2) + ";\n" +
  "if (typeof module === 'object' && module.exports) module.exports = records; else root.KeikyuPositionMap = records;\n" +
  "}(typeof self !== 'undefined' ? self : this));\n");
console.log("Generated " + Object.keys(records).length + " Keikyu positions");
