const assert = require('node:assert/strict');
const fs = require('node:fs');
const adapter = require('../js/tokyu_location_adapter');
const fixture = JSON.parse(fs.readFileSync('testdata/tokyu_vehicle_5000.json','utf8'));
const result = adapter.dentoVehicleFor(fixture,'5103F',1000);
assert.equal(result.outsideTemperature,21.5);
assert.equal(result.showAirMode,true);
assert.equal(result.carDetails.length,10);
assert.deepEqual(result.carDetails[1],{number:2,congestion:2,temperature:27.5,airMode:'除湿'});
assert.equal(adapter.dentoVehicleFor(fixture,'2145F',1000).showAirMode,false);
assert.equal(adapter.dentoVehicleFor(fixture,'2145F',1000).carDetails[0].airMode,'');
const invalid = adapter.dentoVehicleFor({temp:null,cars:[null,{number:2,passenger_rate:0,temp:'',air_mode:null},{number:1,passenger_rate:6,temp:0},{number:1,temp:42},{number:99},{number:3,passenger_rate:99,temp:999}]},'5103F',1000);
assert.equal(invalid.outsideTemperature,null);
assert.deepEqual(invalid.carDetails.map(c=>c.number),[1,2,3]);
assert.equal(invalid.carDetails[0].temperature,0);
assert.equal(invalid.carDetails[0].congestion,6);
assert.equal(invalid.carDetails[1].temperature,null);
assert.equal(invalid.carDetails[1].congestion,null);
assert.equal(invalid.carDetails[2].temperature,null);
console.log('Tokyu vehicle: actual API fixture, temperatures, congestion, 5000-only air modes and invalid values passed.');
